version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install QT
          command: 'add-apt-repository --yes ppa:ubuntu-sdk-team/ppa && apt-get update -qq && apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev && apt-get install qt5-default qttools5-dev-tools qtmultimedia5-dev libqt5multimedia5-plugins'
      - run:
          name: Creating Build Files
          command: 'qmake'
      - run:
          name: Creating Binary Files
          command: 'make'
